<?php

namespace Mytest\TableBundle\Repository;

/**
 * MainTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainTableRepository extends \Doctrine\ORM\EntityRepository
{
}
