<?php

namespace Mytest\TableBundle\Repository;

/**
 * SubTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubTableRepository extends \Doctrine\ORM\EntityRepository
{
}
